[package]
name = "aus_senate"
version = "0.1.0"
authors = ["Michael Sproul <micsproul@gmail.com>"]
license = "GPL-3.0+"

[dependencies]
num = "0.1"
csv = "0.14.4"
rustc-serialize = "0.3.19"

[profile.release]
debug = true
